version: '3.8'
services:
  shwas-core-app:
    image: node:18-alpine
    container_name: shwas_core_service
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - TWILIO_AUTH_TOKEN=your_auth_token_here
      - MQTT_BROKER_URL=mqtt://://hivemq.com
    ports:
      - "3000:3000"
      - "1883:1883"
    volumes:
      - .:/usr/src/app
      - shwas_database_volume:/usr/src/app/database
    working_dir: /usr/src/app
    command: sh -c "npm install && node server.js"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  shwas_database_volume:
    driver: local
